{% set data= load_setup_py_data() %}
package:
  name: "ts-ess-controller"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  string: "py{{ PY_VER | replace('.', '') }}{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"

test:
  requires:
    - ts-conda-build =0.5
    - ts-ess-common
    - ts-tcpip
    - ts-utils
    - pylibftdi
    - aioserial
  source_files:
    - python
    - bin
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-tcpip
    - ts-utils
    - ts-ess-common
    - pylibftdi
    - aioserial
